### ISSUE TITLE
torque heatmap viz.json breaks cartodb setup

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/cartodb.js#476]
Using cartodb.js 3.14.2 with GMaps and getting the following stacktrace:

```no-highlight
can't find cartodb.js file
cdb.core.Log.Backbone.Model.extend.error @ cartodb.js:20
cdb.vis.Loader.cdb.core.Loader.loadModule @ cartodb.js:20
cdb.core.View.extend.loadModules @ cartodb.js:26
(anonymous function) @ cartodb.js:27
window.vizjson @ cartodb.js:20
(anonymous function) @ viz.json?callback=vizjson:1 cartodb.js:20

GET http://maldenma.localhost:3000/null (anonymous function) @ cartodb.js:20
setTimeout (async)cdb.vis.Loader.cdb.core.Loader.loadScript @ cartodb.js:20
cdb.vis.Loader.cdb.core.Loader.loadModule @ cartodb.js:20
cdb.core.View.extend.loadModules @ cartodb.js:26
(anonymous function) @ cartodb.js:27
window.vizjson @ cartodb.js:20
(anonymous function) @ viz.json?callback=vizjson:1
```

Here's the offending viz.json:

```js
{
  "id": "75b8aea6-f7fd-11e4-b9c4-0e853d047bba",
  "version": "0.1.0",
  "title": "MaldenMA_Values",
  "likes": 0,
  "description": null,
  "scrollwheel": false,
  "legends": true,
  "url": null,
  "map_provider": "leaflet",
  "bounds": [
    [
      42.415726,
      -71.091545
    ],
    [
      42.44075,
      -71.023476
    ]
  ],
  "center": "[42.42823989698809, -71.05751037597656]",
  "zoom": 15,
  "updated_at": null,
  "layers": [
    {
      "options": {
        "visible": true,
        "type": "Tiled",
        "default": "true",
        "url": "https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png",
        "subdomains": "abcd",
        "minZoom": "0",
        "maxZoom": "18",
        "name": "Positron",
        "className": "httpscartodbbasemapssglobalsslfastlynetlight_allzxypng",
        "attribution": "© <a href=\"http://www.openstreetmap.org/copyright\">OpenStreetMap<\/a> contributors © <a href= \"http://cartodb.com/attributions#basemaps\">CartoDB<\/a>",
        "urlTemplate": "https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png",
        "id": "8e057f3a-9d98-4e44-b7f7-f460853ff55d",
        "order": 0,
        "parent_id": null
      },
      "infowindow": null,
      "tooltip": null,
      "id": "8e057f3a-9d98-4e44-b7f7-f460853ff55d",
      "order": 0,
      "parent_id": null,
      "children": [],
      "type": "tiled"
    },
    {
      "id": "04ae539b-2f14-4bb2-9cbf-fad2aa7472b8",
      "parent_id": null,
      "children": [],
      "type": "torque",
      "order": 103,
      "legend": {
        "type": "none",
        "show_title": false,
        "title": "",
        "template": "",
        "items": [
          {
            "name": "Left label",
            "visible": true,
            "value": "Less",
            "legend_type": "intensity",
            "type": "text",
            "sync": true
          },
          {
            "name": "Right label",
            "visible": true,
            "value": "More",
            "legend_type": "intensity",
            "type": "text",
            "sync": true
          },
          {
            "name": "Color",
            "visible": true,
            "value": "#FFCC00",
            "type": "color"
          }
        ]
      },
      "options": {
        "stat_tag": "75b8aea6-f7fd-11e4-b9c4-0e853d047bba",
        "maps_api_template": "https://{user}.cartodb.com:443",
        "sql_api_template": "https://{user}.cartodb.com:443",
        "tiler_protocol": "http",
        "tiler_domain": "cartodb.com",
        "tiler_port": "80",
        "sql_api_protocol": "http",
        "sql_api_domain": "cartodb.com",
        "sql_api_endpoint": "/api/v2/sql",
        "sql_api_port": 80,
        "cdn_url": {
          "http": "api.cartocdn.com",
          "https": "cartocdn.global.ssl.fastly.net"
        },
        "layer_name": "maldenma_parcels_joined",
        "dynamic_cdn": false,
        "visible": true,
        "table_name": "maldenma_parcels_joined",
        "user_name": "clientdemos",
        "tile_style": "/** torque_heat visualization */\n\nMap {\n-torque-frame-count:1;\n-torque-animation-duration:10;\n-torque-time-attribute:\"cartodb_id\";\n-torque-aggregation-function:\"count(cartodb_id)\";\n-torque-resolution:8;\n-torque-data-aggregation:linear;\n}\n\n#maldenma_parcels_joined{\n  image-filters: colorize-alpha(blue, cyan, lightgreen, yellow , orange, red);\n  marker-file: url(http://s3.amazonaws.com/com.cartodb.assets.static/alphamarker.png);\n  marker-fill-opacity: 0.7;\n  marker-width: 31.5;\n}",
        "named_map": {
          "name": "tpl_75b8aea6_f7fd_11e4_b9c4_0e853d047bba",
          "layer_index": 0,
          "params": {}
        }
      }
    }
  ],
  "overlays": [
    {
      "type": "logo",
      "order": 9,
      "options": {
        "display": true,
        "x": 10,
        "y": 40
      },
      "template": ""
    },
    {
      "type": "loader",
      "order": 8,
      "options": {
        "display": true,
        "x": 20,
        "y": 150
      },
      "template": "<div class=\"loader\" original-title=\"\"><\/div>"
    },
    {
      "type": "zoom",
      "order": 6,
      "options": {
        "display": true,
        "x": 20,
        "y": 20
      },
      "template": "<a href=\"#zoom_in\" class=\"zoom_in\">+<\/a> <a href=\"#zoom_out\" class=\"zoom_out\">-<\/a>"
    },
    {
      "type": "search",
      "order": 3,
      "options": {
        "display": true,
        "x": 60,
        "y": 20
      },
      "template": ""
    },
    {
      "type": "share",
      "order": 2,
      "options": {
        "display": true,
        "x": 20,
        "y": 20
      },
      "template": ""
    }
  ],
  "prev": null,
  "next": null,
  "transition_options": {
    "time": 0
  }
}
```

But this works:

```js
{
  id: "75b8aea6-f7fd-11e4-b9c4-0e853d047bba",
  version: "0.1.0",
  title: "MaldenMA_Values",
  likes: 0,
  description: null,
  scrollwheel: false,
  legends: true,
  url: null,
  map_provider: "leaflet",
  bounds: [
    [
      42.41572631286041, -71.09154224395752
    ],
    [
      42.44075098356437, -71.0234785079956
    ]
  ],
  center: "[42.42823989698809, -71.05751037597656]",
  zoom: 15,
  updated_at: "2015-05-11T17:49:54+00:00",
  layers: [{}, {
    type: "namedmap",
    order: 1,
    options: {
      type: "namedmap",
      user_name: "clientdemos",
      maps_api_template: "https://{user}.cartodb.com:443",
      sql_api_template: "https://{user}.cartodb.com:443",
      tiler_protocol: "http",
      tiler_domain: "cartodb.com",
      tiler_port: "80",
      cdn_url: {
        http: "api.cartocdn.com",
        https: "cartocdn.global.ssl.fastly.net"
      },
      dynamic_cdn: false,
      named_map: {
        name: "tpl_75b8aea6_f7fd_11e4_b9c4_0e853d047bba",
        stat_tag: "75b8aea6-f7fd-11e4-b9c4-0e853d047bba",
        params: {
          layer0: 1
        },
        layers: [{
          layer_name: "maldenma_parcels_joined",
          interactivity: "cartodb_id",
          visible: true
        }]
      }
    }
  }],
  overlays: [{
    type: "logo",
    order: 9,
    options: {
      display: true,
      x: 10,
      y: 40
    },
    template: ""
  }, {
    type: "loader",
    order: 8,
    options: {
      display: true,
      x: 20,
      y: 150
    },
    template: "<div class='loader' original-title=''></div>"
  }, {
    type: "zoom",
    order: 6,
    options: {
      display: true,
      x: 20,
      y: 20
    },
    template: "<a href='#zoom_in' class'zoom_in'>+</a> <a href='#zoom_out' class='zoom_out'>-</a>"
  }, {
    type: "search",
    order: 3,
    options: {
      display: true,
      x: 60,
      y: 20
    },
    template: ""
  }, {
    type: "share",
    order: 2,
    options: {
      display: true,
      x: 20,
      y: 20
    },
    template: ""
  }],
  prev: null,
  next: null,
  transition_options: {
    time: 0
  }
}
```

**Comment by fdansv** [comment]
Hey @knownasilya , can you pass me the html/js you're using please? I'm not having problems on my end with your viz.json

**Comment by knownasilya** [comment]
```js
// .. `map` is gmap instance
// .. `url` is viz.json
var layer = cartodb.createLayer(map, url, {
    cartodb_logo: false,
    infowindow: false,
    tooltip: false,
    legends: false
});
```

The heatmap layer never hits 'done' or 'error' events.

**Comment by fdansv** [comment]
@knownasilya can you use ```cartodb.createVis``` instead of ```cartodb.createLayer```?

**Comment by knownasilya** [comment]
What's the difference? Will it work for all layers, even if they aren't torque based?

**Comment by knownasilya** [comment]
I get this:

```no-highlight
TypeError: Cannot read property 'defaultView' of undefined
    at G.defaultView.G.defaultView.getComputedStyle.Ea (http://maldenma.localhost:3000/assets/vendor.js:86725:8154)
    at p (http://maldenma.localhost:3000/assets/vendor.js:86721:3035)
    at Object.J.each.J.cssHooks.(anonymous function).get (http://maldenma.localhost:3000/assets/vendor.js:86725:8859)
    at Function.J.extend.css (http://maldenma.localhost:3000/assets/vendor.js:86725:7825)
    at http://maldenma.localhost:3000/assets/vendor.js:86725:30035
    at Function.h.extend.access (http://maldenma.localhost:3000/assets/vendor.js:86721:13408)
    at J.each.J.fn.(anonymous function) [as height] (http://maldenma.localhost:3000/assets/vendor.js:86725:29788)
    at J.each.J.fn.(anonymous function) [as outerHeight] (http://maldenma.localhost:3000/assets/vendor.js:86725:29750)
    at cdb.core.View.extend.load (http://maldenma.localhost:3000/assets/vendor.js:86744:30075)
    at Object.current (http://maldenma.localhost:3000/assets/vendor.js:86744:27896)
```

**Comment by knownasilya** [comment]
Which looks like it's due to google maps not being on a page, since we instantiate it on page load with a DOM element that isn't in the DOM yet. And then we append that element when the page loads.

**Comment by fdansv** [comment]
Have you tried using [our example](https://github.com/CartoDB/cartodb.js/blob/develop/examples/gmaps_with_torque.html) with your viz.json?

**Comment by knownasilya** [comment]
@fdansv using that example in my app I get the first error.

**Comment by knownasilya** [comment]
You can see the issue here: http://maldenma.beta.mapgeo.io (this is with the original code, let me know if you want me to update to `createVis`).

**Comment by knownasilya** [comment]
Looks like it's looking for `cartodb.mod.torque.js` but can't find it. Where do I get that file?

**Comment by knownasilya** [comment]
Ok I built the project and added the file, and now there are no errors. Shouldn't this file be included in the regular build? And why would it try to load it via a script tag? Seems like requiring/looking for a global variable would be best, since most people concatenate their scripts now-a-days..

**Comment by knownasilya** [comment]
Now, when I enable the layer I get an error where it cannot get the `width` of `undefined`, since there is no `tileSize`.. Are torque layers supposed to be added to Google Maps in a different way?
