### ISSUE TITLE
toggling torque layer & setMap(null) error

### ISSUE THREAD

**Issue by knownasilya** [CartoDB/cartodb.js#478]
So currently I add the layer with `setMap`, but that seems to break on off. Also the time slider shows on the map as soon as the layer is created. I only want to show when the layer is shown.

**Comment by knownasilya** [comment]
I know I can set `time_slider` on create, but how can I enable it later on?

**Comment by knownasilya** [comment]
Anyone?

**Comment by javisantana** [comment]
you can't easily, basically calling this function would work https://github.com/CartoDB/cartodb.js/blob/develop/src/vis/vis.js#L224 but it's not official API so it could be changed anytime

**Comment by knownasilya** [comment]
Also it seems if you set `setMap(null)` on a torque layer, you get the following error:

```no-highlight
TypeError: a[Fb] is not a function
    at Object.T.removeListener (http://maps.gstatic.com/maps-api-v3/api/js/19/17/main.js:17:1368)
    at Uk.d._removeTileLoader (http://localhost:3000/assets/cartodb.mod.torque.js:7:13923)
    at Uk.g.extend.onRemove (http://localhost:3000/assets/cartodb.mod.torque.js:7:21642)
    at Uk.dT (eval at <anonymous> (eval at <anonymous> (http://maps.gstatic.com/maps-api-v3/api/js/19/17/main.js:59:931)), <anonymous>:1:432)
    at fT.ma (http://maps.gstatic.com/maps-api-v3/api/js/19/17/main.js:16:335)
    at gT.(anonymous function).j (eval at <anonymous> (eval at <anonymous> (http://maps.gstatic.com/maps-api-v3/api/js/19/17/main.js:59:931)), <anonymous>:2:192)
    at http://maps.gstatic.com/maps-api-v3/api/js/19/17/main.js:55:932
    at dg (http://maps.gstatic.com/maps-api-v3/api/js/19/17/main.js:28:432)
    at Uk.map_changed (http://maps.gstatic.com/maps-api-v3/api/js/19/17/main.js:55:905)
    at jf (http://maps.gstatic.com/maps-api-v3/api/js/19/17/main.js:22:190)
```

**Comment by knownasilya** [comment]
Looks like a `remove()` doesn't exist on the `panes_changed` event?

**Comment by knownasilya** [comment]
@javisantana could we make it public API where you can change the layer options after you create the layer? Kinda like google maps `setOptions(hash)`?

**Comment by knownasilya** [comment]
Tried

```js
var v = new cdb.vis.Vis();
v.addTimeSlider(layer);
```

But a `mapView` is missing, and I'm not sure how that works.

**Comment by javisantana** [comment]
Could you share a full example ? It's really hard to see what is the way you are using the torque layer

**Comment by knownasilya** [comment]
```js
var layer = cartodb.createLayer(map, options.url, {
      cartodb_logo: false,
      infowindow: false,
      tooltip: false,
      legends: false,
      time_slider: false
    });

    layer.on('done', function (layer) {
      if (typeof layer.setInteraction === 'function') {
        layer.setInteraction(false);
      }

      if (layer.pause) {
        layer.pause();
      }
  });
```

Something along those lines, where I do `setMap` when I want to enable to torque layer in the UI.

**Comment by javisantana** [comment]
ohhh, ok, I though you were using createVis.

Internally createLayer creates a visualization and it's store in map.viz (yes, ``map`` is the map instance) so you could do map.viz. addTimeSlider(layer)

That's not the way and this should be done using the api:

```
var slider = new cdb.geo.ui.TimeSlider({ layer: layer });
$('#map').append(slider.render().el)
```

cc @alonsogarciapablo

**Comment by knownasilya** [comment]
Ok, I got it working here: http://maldenma.beta.mapgeo.io/ (click layer icon in top right and select on of the animated layers at the bottom).

It seems like the play/pause controls don't get toggled.

**Comment by nobuti** [comment]
There has been no activity on this issue for several months and that's why are closing it (automatically). If you think this still needs to be addressed please reopen it. The good news is that we are now working on the next version of CARTO.js, stay tuned.
